set echo on
set lines 1000
set trimspool on
spool setParam.log


conn / as sysdba


PROMPT
PROMPT 创建表空间....
PROMPT

CREATE SMALLFILE TABLESPACE "HSHIS" DATAFILE 
  'D:\app\Administrator\oradata\his\HSHIS1' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER TABLESPACE  "HSHIS"  ADD DATAFILE 
  'D:\app\Administrator\oradata\his\HSHIS2'  SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M;


CREATE SMALLFILE TABLESPACE "HSIND" DATAFILE
  'D:\app\Administrator\oradata\his\HSIND1' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

ALTER TABLESPACE  "HSIND"  ADD DATAFILE 
  'D:\app\Administrator\oradata\his\HSIND2'  SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M;

CREATE SMALLFILE  TABLESPACE CHARGE_BILL_P LOGGING 
  datafile 'D:\app\Administrator\oradata\his\charge_bill.dbf' 
  size 128k reuse autoextend on next 10m maxsize 8000m
  default storage (initial 20k next 10m pctincrease 0);

CREATE SMALLFILE  TABLESPACE CHARGE_ITEM_P LOGGING 
  DATAFILE 'D:\app\Administrator\oradata\his\CHARGE_ITEM.DBF' 
  SIZE 128K REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 8000M
  DEFAULT STORAGE (INITIAL 20K NEXT 10M PCTINCREASE 0);

CREATE SMALLFILE  TABLESPACE CHARGE_FEE_DATA LOGGING 
  DATAFILE 'D:\app\Administrator\oradata\his\CHARGE_FEE_DATE.DBF' 
  SIZE 128K REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 8000M
  DEFAULT STORAGE (INITIAL 20K NEXT 10M PCTINCREASE 0);

CREATE SMALLFILE  TABLESPACE CIRCULATION_DETAIL_P LOGGING 
  DATAFILE 'D:\app\Administrator\oradata\his\CIRCULATION_DETAIL.DBF' 
  SIZE 128K REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 8000M
  DEFAULT STORAGE (INITIAL 20K NEXT 10M PCTINCREASE 0);

create SMALLFILE tablespace PATIENT_P datafile
 'D:\app\Administrator\oradata\his\patient_p.dbf'
 size 128k reuse autoextend on next 1M maxsize 500M
  default storage (initial 20k next 1m pctincrease 0);

create SMALLFILE tablespace PRESCRIPTION_P datafile
 'D:\app\Administrator\oradata\his\PRESCRIPTION_P.dbf'
 size 128k reuse autoextend on next 10M maxsize 8000M
  default storage (initial 20k next 10m pctincrease 0);

CREATE SMALLFILE  TABLESPACE PRESCRIPTION_DETAIL_P LOGGING 
  DATAFILE 'D:\app\Administrator\oradata\his\PRESCRIPTION_DETAIL_P.DBF' 
  SIZE 128K REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 8000M
  DEFAULT STORAGE (INITIAL 20K NEXT 10M PCTINCREASE 0);

CREATE SMALLFILE  TABLESPACE ORDER_LIST_P LOGGING 
  DATAFILE 'D:\app\Administrator\oradata\his\ORDER_LIST_P.DBF' 
  SIZE 128K REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 8000M
  DEFAULT STORAGE (INITIAL 20K NEXT 10M PCTINCREASE 0);

CREATE SMALLFILE  TABLESPACE CHARGE_STATIS_P LOGGING 
  datafile 'D:\app\Administrator\oradata\his\CHARGE_STATIS_P.dbf' 
  size 128k reuse autoextend on next 5m maxsize 8000m
  default storage (initial 20k next 5m pctincrease 0);

CREATE SMALLFILE  TABLESPACE HSCENTER LOGGING 
  DATAFILE 'D:\app\Administrator\oradata\his\HSCENTER.DBF' 
  SIZE 128K REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 8000M
  DEFAULT STORAGE (INITIAL 20K NEXT 10M PCTINCREASE 0);

CREATE SMALLFILE  TABLESPACE HSEMR_TAB LOGGING 
  DATAFILE 'D:\app\Administrator\oradata\his\HSEMR_TAB.DBF' 
  SIZE 128K REUSE AUTOEXTEND ON NEXT 10M MAXSIZE 8000M
  DEFAULT STORAGE (INITIAL 20K NEXT 10M PCTINCREASE 0);


CREATE SMALLFILE TABLESPACE "ECASETAB" DATAFILE 
  'D:\app\Administrator\oradata\his\ECASETAB01.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


CREATE SMALLFILE TABLESPACE "ECASEIND" DATAFILE
  'D:\app\Administrator\oradata\his\ECASEIND01.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HSDOC" DATAFILE
  'D:\app\Administrator\oradata\his\HSDOC1.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M  MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "EBLD" DATAFILE
  'D:\app\Administrator\oradata\his\EBLD1.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "EBLI" DATAFILE
  'D:\app\Administrator\oradata\his\EBLI1.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HRMSTAB" DATAFILE
  'D:\app\Administrator\oradata\his\HRMSTAB.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HRMSIND" DATAFILE
  'D:\app\Administrator\oradata\his\HRMSIND.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


CREATE SMALLFILE TABLESPACE "INSURANCE_TS" DATAFILE
  'D:\app\Administrator\oradata\his\INSURANCE_TS.DBF' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 8001M
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

create SMALLFILE tablespace "hsmc_ts"
datafile 'D:\app\Administrator\oradata\his\hsmc_ts.dbf' size 10m
autoextend on next 10m maxsize 2048m
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

create SMALLFILE tablespace "hsmc_indts"
datafile 'D:\app\Administrator\oradata\his\hsmc_indts.dbf' size 10m
autoextend on next 10m maxsize 2048m
  LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

PROMPT
PROMPT 创建用户HOSPITAL...
PROMPT

CREATE USER "HOSPITAL"  PROFILE "DEFAULT" IDENTIFIED BY "source" DEFAULT TABLESPACE "HSHIS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HOSPITAL";
GRANT "RESOURCE" TO "HOSPITAL";
GRANT CREATE SESSION TO "HOSPITAL";
GRANT CREATE SYNONYM TO "HOSPITAL";
GRANT CREATE TABLE TO "HOSPITAL";
GRANT CREATE TABLESPACE TO "HOSPITAL";
GRANT DROP TABLESPACE TO "HOSPITAL";
GRANT CREATE TRIGGER TO "HOSPITAL";
GRANT CREATE TYPE TO "HOSPITAL";
GRANT CREATE VIEW TO "HOSPITAL";
GRANT CREATE SEQUENCE TO "HOSPITAL";
GRANT DBA TO "HOSPITAL";
GRANT EXECUTE ON DBMS_ALERT TO "HOSPITAL";
GRANT EXECUTE ON DBMS_CRYPTO TO "HOSPITAL";

CREATE USER "HUMAN"  PROFILE "DEFAULT" IDENTIFIED BY "RES" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HUMAN";
GRANT "RESOURCE" TO "HUMAN";
GRANT CREATE SESSION TO "HUMAN";
GRANT CREATE SYNONYM TO "HUMAN";
GRANT CREATE TABLE TO "HUMAN";
GRANT CREATE TABLESPACE TO "HUMAN";
GRANT DROP TABLESPACE TO "HUMAN";
GRANT CREATE TRIGGER TO "HUMAN";
GRANT CREATE TYPE TO "HUMAN";
GRANT CREATE VIEW TO "HUMAN";
GRANT CREATE SEQUENCE TO "HUMAN";

CREATE USER "ZDWXAPI"  PROFILE "DEFAULT" IDENTIFIED BY "ZDWXAPI" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "ZDWXAPI" ;
GRANT "RESOURCE" TO "ZDWXAPI";
GRANT CREATE SESSION TO "ZDWXAPI";
GRANT CREATE SYNONYM TO "ZDWXAPI";
GRANT CREATE TABLE TO "ZDWXAPI";
GRANT CREATE TABLESPACE TO "ZDWXAPI";
GRANT DROP TABLESPACE TO "ZDWXAPI";
GRANT CREATE TRIGGER TO "ZDWXAPI";
GRANT CREATE TYPE TO "ZDWXAPI";
GRANT CREATE VIEW TO "ZDWXAPI";
GRANT CREATE SEQUENCE TO "ZDWXAPI";


CREATE USER "HOSPREAD" PROFILE "DEFAULT" IDENTIFIED BY "HOSPREAD" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HOSPREAD" ;
GRANT "RESOURCE" TO "HOSPREAD" ;
GRANT CREATE SESSION TO "HOSPREAD" ;
GRANT CREATE SYNONYM TO "HOSPREAD" ;
GRANT CREATE TABLE TO "HOSPREAD" ;
GRANT CREATE TABLESPACE TO "HOSPREAD" ;
GRANT DROP TABLESPACE TO "HOSPREAD" ;
GRANT CREATE TRIGGER TO "HOSPREAD" ;
GRANT CREATE TYPE TO "HOSPREAD" ;
GRANT CREATE VIEW TO "HOSPREAD" ;
GRANT CREATE SEQUENCE TO "HOSPREAD" ;

CREATE USER "HOSP" PROFILE "DEFAULT" IDENTIFIED BY "HOSP" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HOSP" ;
GRANT "RESOURCE" TO "HOSP" ;
GRANT CREATE SESSION TO "HOSP" ;
GRANT CREATE SYNONYM TO "HOSP" ;
GRANT CREATE TABLE TO "HOSP" ;
GRANT CREATE TABLESPACE TO "HOSP" ;
GRANT DROP TABLESPACE TO "HOSP" ;
GRANT CREATE TRIGGER TO "HOSP" ;
GRANT CREATE TYPE TO "HOSP" ;
GRANT CREATE VIEW TO "HOSP" ;
GRANT CREATE SEQUENCE TO "HOSP" ;

CREATE USER "HSCENTER" PROFILE "DEFAULT" IDENTIFIED BY "HSCENTER" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSCENTER" ;
GRANT "RESOURCE" TO "HSCENTER" ;
GRANT CREATE SESSION TO "HSCENTER" ;
GRANT CREATE SYNONYM TO "HSCENTER" ;
GRANT CREATE TABLE TO "HSCENTER" ;
GRANT CREATE TABLESPACE TO "HSCENTER" ;
GRANT DROP TABLESPACE TO "HSCENTER" ;
GRANT CREATE TRIGGER TO "HSCENTER" ;
GRANT CREATE TYPE TO "HSCENTER" ;
GRANT CREATE VIEW TO "HSCENTER" ;
GRANT CREATE SEQUENCE TO "HSCENTER" ;

CREATE USER "HSINS" PROFILE "DEFAULT" IDENTIFIED BY "HSINS" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSINS" ;
GRANT "RESOURCE" TO "HSINS" ;
GRANT CREATE SESSION TO "HSINS" ;
GRANT CREATE SYNONYM TO "HSINS" ;
GRANT CREATE TABLE TO "HSINS" ;
GRANT CREATE TABLESPACE TO "HSINS" ;
GRANT DROP TABLESPACE TO "HSINS" ;
GRANT CREATE TRIGGER TO "HSINS" ;
GRANT CREATE TYPE TO "HSINS" ;
GRANT CREATE VIEW TO "HSINS" ;
GRANT CREATE SEQUENCE TO "HSINS" ;

CREATE USER "HSINS_MI" PROFILE "DEFAULT" IDENTIFIED BY "HSINS_MI" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSINS_MI" ;
GRANT "RESOURCE" TO "HSINS_MI" ;
GRANT CREATE SESSION TO "HSINS_MI" ;
GRANT CREATE SYNONYM TO "HSINS_MI" ;
GRANT CREATE TABLE TO "HSINS_MI" ;
GRANT CREATE TABLESPACE TO "HSINS_MI" ;
GRANT DROP TABLESPACE TO "HSINS_MI" ;
GRANT CREATE TRIGGER TO "HSINS_MI" ;
GRANT CREATE TYPE TO "HSINS_MI" ;
GRANT CREATE VIEW TO "HSINS_MI" ;
GRANT CREATE SEQUENCE TO "HSINS_MI" ;

CREATE USER "HSEMR" PROFILE "DEFAULT" IDENTIFIED BY "HSEMR" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSEMR" ;
GRANT "RESOURCE" TO "HSEMR" ;
GRANT CREATE SESSION TO "HSEMR" ;
GRANT CREATE SYNONYM TO "HSEMR" ;
GRANT CREATE TABLE TO "HSEMR" ;
GRANT CREATE TABLESPACE TO "HSEMR" ;
GRANT DROP TABLESPACE TO "HSEMR" ;
GRANT CREATE TRIGGER TO "HSEMR" ;
GRANT CREATE TYPE TO "HSEMR" ;
GRANT CREATE VIEW TO "HSEMR" ;
GRANT CREATE SEQUENCE TO "HSEMR" ;

CREATE USER "LZYB" PROFILE "DEFAULT" IDENTIFIED BY "LZYB" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "LZYB" ;
GRANT "RESOURCE" TO "LZYB" ;
GRANT CREATE SESSION TO "LZYB" ;
GRANT CREATE SYNONYM TO "LZYB" ;
GRANT CREATE TABLE TO "LZYB" ;
GRANT CREATE TABLESPACE TO "LZYB" ;
GRANT DROP TABLESPACE TO "LZYB" ;
GRANT CREATE TRIGGER TO "LZYB" ;
GRANT CREATE TYPE TO "LZYB" ;
GRANT CREATE VIEW TO "LZYB" ;
GRANT CREATE SEQUENCE TO "LZYB" ;

CREATE USER "ZLYB" PROFILE "DEFAULT" IDENTIFIED BY "ZLYB" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "ZLYB" ;
GRANT "RESOURCE" TO "ZLYB" ;
GRANT CREATE SESSION TO "ZLYB" ;
GRANT CREATE SYNONYM TO "ZLYB" ;
GRANT CREATE TABLE TO "ZLYB" ;
GRANT CREATE TABLESPACE TO "ZLYB" ;
GRANT DROP TABLESPACE TO "ZLYB" ;
GRANT CREATE TRIGGER TO "ZLYB" ;
GRANT CREATE TYPE TO "ZLYB" ;
GRANT CREATE VIEW TO "ZLYB" ;
GRANT CREATE SEQUENCE TO "ZLYB" ;

CREATE USER "HSCONTRL" PROFILE "DEFAULT" IDENTIFIED BY "HSCONTRL" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSCONTRL" ;
GRANT "RESOURCE" TO "HSCONTRL" ;
GRANT CREATE SESSION TO "HSCONTRL" ;
GRANT CREATE SYNONYM TO "HSCONTRL" ;
GRANT CREATE TABLE TO "HSCONTRL" ;
GRANT CREATE TABLESPACE TO "HSCONTRL" ;
GRANT DROP TABLESPACE TO "HSCONTRL" ;
GRANT CREATE TRIGGER TO "HSCONTRL" ;
GRANT CREATE TYPE TO "HSCONTRL" ;
GRANT CREATE VIEW TO "HSCONTRL" ;
GRANT CREATE SEQUENCE TO "HSCONTRL" ;

CREATE USER "COMED"  PROFILE "DEFAULT" IDENTIFIED BY "COMED" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "COMED"  ;
GRANT "RESOURCE" TO "COMED"  ;
GRANT CREATE SESSION TO "COMED"  ;
GRANT CREATE SYNONYM TO "COMED"  ;
GRANT CREATE TABLE TO "COMED"  ;
GRANT CREATE TABLESPACE TO "COMED"  ;
GRANT CREATE TRIGGER TO "COMED"  ;
GRANT CREATE TYPE TO "COMED"  ;
GRANT CREATE VIEW TO "COMED"  ;
GRANT CREATE SEQUENCE TO "COMED"  ;

CREATE USER "HSOPER"  PROFILE "DEFAULT" IDENTIFIED BY "OPERS" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSOPER"  ;
GRANT "RESOURCE" TO "HSOPER"  ;
GRANT CREATE SESSION TO "HSOPER"  ;
GRANT CREATE SYNONYM TO "HSOPER"  ;
GRANT CREATE TABLE TO "HSOPER"  ;
GRANT CREATE TABLESPACE TO "HSOPER"  ;
GRANT CREATE TRIGGER TO "HSOPER"  ;
GRANT CREATE TYPE TO "HSOPER"  ;
GRANT CREATE VIEW TO "HSOPER"  ;
GRANT CREATE SEQUENCE TO "HSOPER"  ;

CREATE USER "HSDOC"  PROFILE "DEFAULT" IDENTIFIED BY "docpwd" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSDOC"  ;
GRANT "RESOURCE" TO "HSDOC"  ;
GRANT CREATE SESSION TO "HSDOC"  ;
GRANT CREATE SYNONYM TO "HSDOC"  ;
GRANT CREATE TABLE TO "HSDOC"  ;
GRANT CREATE TABLESPACE TO "HSDOC"  ;
GRANT CREATE TRIGGER TO "HSDOC"  ;
GRANT CREATE TYPE TO "HSDOC"  ;
GRANT CREATE VIEW TO "HSDOC"  ;
GRANT CREATE SEQUENCE TO "HSDOC"  ;

CREATE ROLE "HSHIS_USER"  NOT IDENTIFIED;
CREATE USER H_001001  PROFILE "DEFAULT" IDENTIFIED BY H_TIGER DEFAULT TABLESPACE "HSHIS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT CONNECT TO H_001001;
GRANT CREATE SESSION TO H_001001;
GRANT HSHIS_USER TO H_001001;

CREATE USER "EBL"  PROFILE "DEFAULT" IDENTIFIED BY "EBL" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "EBL"  ;
GRANT "RESOURCE" TO "EBL"  ;
GRANT CREATE SESSION TO "EBL"  ;
GRANT CREATE SYNONYM TO "EBL"  ;
GRANT CREATE TABLE TO "EBL"  ;
GRANT CREATE TABLESPACE TO "EBL"  ;
GRANT CREATE TRIGGER TO "EBL"  ;
GRANT CREATE TYPE TO "EBL"  ;
GRANT CREATE VIEW TO "EBL"  ;
GRANT CREATE SEQUENCE TO "EBL"  ;

CREATE USER "PACSIF"  PROFILE "DEFAULT" IDENTIFIED BY "PACSIF" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "PACSIF"  ;
GRANT "RESOURCE" TO "PACSIF"  ;
GRANT CREATE SESSION TO "PACSIF"  ;
GRANT CREATE SYNONYM TO "PACSIF"  ;
GRANT CREATE TABLE TO "PACSIF"  ;
GRANT CREATE TABLESPACE TO "PACSIF"  ;
GRANT CREATE TRIGGER TO "PACSIF"  ;
GRANT CREATE TYPE TO "PACSIF"  ;
GRANT CREATE VIEW TO "PACSIF"  ;
GRANT CREATE SEQUENCE TO "PACSIF"  ;


CREATE USER "QYYB"  PROFILE "DEFAULT" IDENTIFIED BY "QYYB" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "QYYB"  ;
GRANT "RESOURCE" TO "QYYB"  ;
GRANT CREATE SESSION TO "QYYB"  ;
GRANT CREATE SYNONYM TO "QYYB"  ;
GRANT CREATE TABLE TO "QYYB"  ;
GRANT CREATE TABLESPACE TO "QYYB"  ;
GRANT CREATE TRIGGER TO "QYYB"  ;
GRANT CREATE TYPE TO "QYYB"  ;
GRANT CREATE VIEW TO "QYYB"  ;
GRANT CREATE SEQUENCE TO "QYYB"  ;

CREATE USER "LISIF"  PROFILE "DEFAULT" IDENTIFIED BY "LISIF" DEFAULT TABLESPACE  "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "LISIF"  ;
GRANT "RESOURCE" TO "LISIF"  ;
GRANT CREATE SESSION TO "LISIF"  ;
GRANT CREATE SYNONYM TO "LISIF"  ;
GRANT CREATE TABLE TO "LISIF"  ;
GRANT CREATE TABLESPACE TO "LISIF"  ;
GRANT DROP TABLESPACE TO "LISIF"  ;
GRANT CREATE TRIGGER TO "LISIF"  ;
GRANT CREATE TYPE TO "LISIF"  ;
GRANT CREATE VIEW TO "LISIF"  ;
GRANT CREATE SEQUENCE TO "LISIF"  ;


CREATE USER "MEDINSURE"  PROFILE "DEFAULT" IDENTIFIED BY "MEDINSURE" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "MEDINSURE";  
GRANT "RESOURCE" TO "MEDINSURE"  ;
GRANT CREATE SESSION TO "MEDINSURE"  ;
GRANT CREATE SYNONYM TO "MEDINSURE"  ;
GRANT CREATE TABLE TO "MEDINSURE"  ;
GRANT CREATE TABLESPACE TO "MEDINSURE"  ;
GRANT CREATE TRIGGER TO "MEDINSURE"  ;
GRANT CREATE TYPE TO "MEDINSURE"  ;
GRANT CREATE VIEW TO "MEDINSURE"  ;
GRANT CREATE SEQUENCE TO "MEDINSURE" ;

CREATE USER "HSTEND"  PROFILE "DEFAULT" IDENTIFIED BY "TENDS" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSTEND"  ;
GRANT "RESOURCE" TO "HSTEND"  ;
GRANT CREATE SESSION TO "HSTEND"  ;
GRANT CREATE SYNONYM TO "HSTEND"  ;
GRANT CREATE TABLE TO "HSTEND"  ;
GRANT CREATE TABLESPACE TO "HSTEND"  ;
GRANT CREATE TRIGGER TO "HSTEND"  ;
GRANT CREATE TYPE TO "HSTEND"  ;
GRANT CREATE VIEW TO "HSTEND"  ;
GRANT CREATE SEQUENCE TO "HSTEND"  ;
GRANT "HSHIS_USER" TO "HSTEND"  ;

CREATE USER "HSECASE"  PROFILE "DEFAULT" IDENTIFIED BY "ECASES" DEFAULT TABLESPACE "HRMSTAB" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSECASE"  ;
GRANT "RESOURCE" TO "HSECASE"  ;
GRANT CREATE SESSION TO "HSECASE"  ;
GRANT CREATE SYNONYM TO "HSECASE"  ;
GRANT CREATE TABLE TO "HSECASE"  ;
GRANT CREATE TABLESPACE TO "HSECASE"  ;
GRANT CREATE TRIGGER TO "HSECASE"  ;
GRANT CREATE TYPE TO "HSECASE"  ;
GRANT CREATE VIEW TO "HSECASE"  ;
GRANT CREATE SEQUENCE TO "HSECASE"  ;
GRANT "HSHIS_USER" TO "HSECASE"  ;

CREATE USER "HSMC"  PROFILE "DEFAULT" IDENTIFIED BY "MCS" DEFAULT TABLESPACE "hsmc_ts" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSMC"  ;
GRANT "RESOURCE" TO "HSMC"  ;
GRANT CREATE SESSION TO "HSMC"  ;
GRANT CREATE SYNONYM TO "HSMC"  ;
GRANT CREATE TABLE TO "HSMC"  ;
GRANT CREATE TABLESPACE TO "HSMC"  ;
GRANT CREATE TRIGGER TO "HSMC" ; 
GRANT CREATE TYPE TO "HSMC"  ;
GRANT CREATE VIEW TO "HSMC"  ;
GRANT CREATE SEQUENCE TO "HSMC"  ;
grant hshis_user to "HSMC"  ;

CREATE USER "HSCITYMC"  PROFILE "DEFAULT" IDENTIFIED BY "CITYMCS" DEFAULT TABLESPACE "hsmc_ts" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSCITYMC"  ;
GRANT "RESOURCE" TO "HSCITYMC"  ;
GRANT CREATE SESSION TO "HSCITYMC"  ;
GRANT CREATE SYNONYM TO "HSCITYMC"  ;
GRANT CREATE TABLE TO "HSCITYMC"  ;
GRANT CREATE TABLESPACE TO "HSCITYMC"  ;
GRANT CREATE TRIGGER TO "HSCITYMC"  ; 
GRANT CREATE TYPE TO "HSCITYMC"  ;
GRANT CREATE VIEW TO "HSCITYMC"  ;
GRANT CREATE SEQUENCE TO "HSCITYMC"  ;
grant hshis_user to "HSCITYMC"  ;

CREATE USER CooperateHis PROFILE "DEFAULT" IDENTIFIED BY CooperateHis1 DEFAULT TABLESPACE "INSURANCE_TS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO CooperateHis;
GRANT "RESOURCE" TO CooperateHis;
GRANT CREATE SESSION TO CooperateHis;
GRANT CREATE SYNONYM TO CooperateHis;
GRANT CREATE TABLE TO CooperateHis;
GRANT CREATE TABLESPACE TO CooperateHis;
GRANT CREATE TRIGGER TO CooperateHis; 
GRANT CREATE TYPE TO CooperateHis;
GRANT CREATE VIEW TO CooperateHis;
GRANT CREATE SEQUENCE TO CooperateHis;
grant hshis_user to CooperateHis;

CREATE USER "HSRPT" PROFILE "DEFAULT" IDENTIFIED BY "HSRPT" DEFAULT TABLESPACE "HSHIS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "HSRPT" ;
GRANT "RESOURCE" TO "HSRPT" ;
GRANT CREATE SESSION TO "HSRPT" ;
GRANT CREATE SYNONYM TO "HSRPT" ;
GRANT CREATE TABLE TO "HSRPT" ;
GRANT CREATE TABLESPACE TO "HSRPT" ;
GRANT CREATE TRIGGER TO "HSRPT" ;
GRANT CREATE TYPE TO "HSRPT" ;
GRANT CREATE VIEW TO "HSRPT" ;
GRANT CREATE SEQUENCE TO "HSRPT" ;
grant hshis_user to "HSRPT" ;

CREATE USER "VER"  PROFILE "DEFAULT" IDENTIFIED BY "TIGER" DEFAULT TABLESPACE "HSHIS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "VER";
GRANT "RESOURCE" TO "VER";
GRANT CREATE SESSION TO "VER";

PROMPT
PROMPT 创建分区表....
PROMPT

conn hospital/source

@ctab\charge_bill_a01.SQL
@ctab\charge_item_a01.sql
@ctab\circulation_detail_a01.SQL
@ctab\circulation_ticket_a01.SQL
@ctab\patient.SQL
@ctab\prescription_a01.SQL
@ctab\prescription_detail_a01.SQL
@ctab\order_list_a01.SQL
@ctab\charge_statistics.SQL
@ctab\rpt_sf_dd.SQL
@ctab\trigs.sql
@ctab\crt_user_hsdoc.sql

spool off

exit