prompt PL/SQL Developer import file
prompt Created on 2016年3月13日 星期日 by Administrator
set feedback off
set define off
prompt Disabling triggers for FIELD_DICT...
alter table FIELD_DICT disable all triggers;
prompt Loading FIELD_DICT...
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'OPEN_MODE', '0', '按病历打开', 'USER', 'ENABLED', '0', to_date('30-09-2015 11:06:21', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历打开模式', null, 'ABLDK');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'OPEN_MODE', '1', '按病程打开', 'USER', 'ENABLED', '1', to_date('30-09-2015 11:06:21', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历打开模式', null, 'ABCDK');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'OPEN_MODE', '2', '按护理记录打开', 'USER', 'ENABLED', '2', to_date('30-09-2015 11:06:21', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历打开模式', null, 'AHLJLDK');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'SHARE_MODE', '0', '全院共享', 'USER', 'ENABLED', '0', to_date('30-09-2015 11:09:30', 'dd-mm-yyyy hh24:mi:ss'), '001001', '共享标志', null, 'WYGX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'SHARE_MODE', '1', '科室共享', 'USER', 'ENABLED', '1', to_date('30-09-2015 11:09:30', 'dd-mm-yyyy hh24:mi:ss'), '001001', '共享标志', null, 'KSGX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'DATE_FORMAT', '0', 'YYYY-MM-DD HH:MI', 'SYSTEM', 'ENABLED', '0', to_date('10-10-2015 16:11:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '时间格式', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'DATE_FORMAT', '1', 'YYYY-MM-DD', 'SYSTEM', 'ENABLED', '1', to_date('10-10-2015 16:11:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '时间格式', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'DATE_FORMAT', '2', 'YYYY-MM-DD HH', 'SYSTEM', 'ENABLED', '2', to_date('10-10-2015 16:11:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '时间格式', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'DATE_FORMAT', '3', 'YYYY-MM-DD,HH:MI', 'SYSTEM', 'ENABLED', '3', to_date('10-10-2015 16:11:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '时间格式', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'DATE_FORMAT', '4', 'YYYY-M月-D日 HH:MI', 'SYSTEM', 'ENABLED', '4', to_date('10-10-2015 16:11:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '时间格式', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'DATE_FORMAT', '5', 'YYYY年M月D日 HH:MI', 'SYSTEM', 'ENABLED', '5', to_date('10-10-2015 16:11:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '时间格式', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_CONTENT_IO_AMOUNT', 'TYPE', 'I', '入量', 'SYSTEM', 'ENABLED', '0', to_date('11-10-2015 09:55:45', 'dd-mm-yyyy hh24:mi:ss'), '001001', '入量', null, 'RL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_CONTENT_IO_AMOUNT', 'TYPE', 'O', '出量', 'SYSTEM', 'ENABLED', '1', to_date('11-10-2015 09:55:45', 'dd-mm-yyyy hh24:mi:ss'), '001001', '出量', null, 'CL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_CONTENT_IO_AMOUNT_', 'TYPE', 'I', '入量', 'SYSTEM', 'ENABLED', '0', to_date('11-10-2015 09:56:36', 'dd-mm-yyyy hh24:mi:ss'), '001001', '入量', null, 'RL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_CONTENT_IO_AMOUNT_', 'TYPE', 'O', '出量', 'SYSTEM', 'ENABLED', '1', to_date('11-10-2015 09:56:36', 'dd-mm-yyyy hh24:mi:ss'), '001001', '出量', null, 'CL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_NURSE_RECORD_', 'SUMMARY_FLAG', '2', '小夜班小结', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 10:19:03', 'dd-mm-yyyy hh24:mi:ss'), '001001', '23:00小夜班小结', null, 'XYBXJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_NURSE_RECORD_', 'SUMMARY_FLAG', '3', '大夜班小结', 'SYSTEM', 'ENABLED', '3', to_date('11-10-2015 10:19:03', 'dd-mm-yyyy hh24:mi:ss'), '001001', '07:59大夜班小结', null, 'DYBXJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_NURSE_RECORD_', 'SUMMARY_FLAG', '4', '24小时总结 ', 'SYSTEM', 'ENABLED', '4', to_date('11-10-2015 10:19:03', 'dd-mm-yyyy hh24:mi:ss'), '001001', '08:0024小时总结', null, 'ESSXSZJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DATA_SET_VS_DG_OR_DE_', 'TYPE', '0', '数据元', 'SYSTEM', 'ENABLED', '1', to_date('11-10-2015 14:31:37', 'dd-mm-yyyy hh24:mi:ss'), '001001', '数据类型', null, 'SJY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DATA_SET_VS_DG_OR_DE_', 'TYPE', '1', '数据组', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:31:37', 'dd-mm-yyyy hh24:mi:ss'), '001001', '数据类型', null, 'SJZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_NURSE_RECORD_', 'SUMMARY_FLAG', '0', '一般', 'SYSTEM', 'ENABLED', '0', to_date('11-10-2015 10:19:03', 'dd-mm-yyyy hh24:mi:ss'), '001001', '一般患者记录单', null, 'YB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_NURSE_RECORD_', 'SUMMARY_FLAG', '1', '白班小结', 'SYSTEM', 'ENABLED', '1', to_date('11-10-2015 10:19:03', 'dd-mm-yyyy hh24:mi:ss'), '001001', '17:30白班小结', null, 'BBXJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'FILE_EDIT_APPLY_PRIORITY', '0', '无', 'SYSTEM', 'ENABLED', '0', to_date('10-10-2015 16:12:58', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历编辑申请等级', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'NEED_SUPERIOR_SIGNATURE', '0', '经治审签', 'SYSTEM', 'ENABLED', '0', to_date('10-10-2015 16:17:17', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审签等级', null, 'JZSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'NEED_SUPERIOR_SIGNATURE', '1', '主治审签', 'SYSTEM', 'ENABLED', '1', to_date('10-10-2015 16:17:17', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审签等级', null, 'ZZSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'NEED_SUPERIOR_SIGNATURE', '2', '主任审签', 'SYSTEM', 'ENABLED', '2', to_date('10-10-2015 16:17:17', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审签等级', null, 'ZRSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'NEED_SUPERIOR_SIGNATURE', '3', '科主任审签', 'SYSTEM', 'ENABLED', '3', to_date('10-10-2015 16:17:17', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审签等级', null, 'KZRSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'SIGNATURE_NEED_DIAGNOSE', '0', '无', 'SYSTEM', 'ENABLED', '0', to_date('10-10-2015 16:17:48', 'dd-mm-yyyy hh24:mi:ss'), '001001', '提交文档要求', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'SIGNATURE_NEED_DIAGNOSE', '1', '初步诊断', 'SYSTEM', 'ENABLED', '1', to_date('10-10-2015 16:17:48', 'dd-mm-yyyy hh24:mi:ss'), '001001', '提交文档要求', null, 'CBZD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'SIGNATURE_NEED_DIAGNOSE', '2', '补充诊断', 'SYSTEM', 'ENABLED', '2', to_date('10-10-2015 16:17:48', 'dd-mm-yyyy hh24:mi:ss'), '001001', '提交文档要求', null, 'BCZD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'SIGNATURE_NEED_DIAGNOSE', '3', '修正诊断', 'SYSTEM', 'ENABLED', '3', to_date('10-10-2015 16:17:48', 'dd-mm-yyyy hh24:mi:ss'), '001001', '提交文档要求', null, 'XZZD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'SIGNATURE_NEED_DIAGNOSE', '4', '最后诊断', 'SYSTEM', 'ENABLED', '4', to_date('10-10-2015 16:17:49', 'dd-mm-yyyy hh24:mi:ss'), '001001', '提交文档要求', null, 'ZHZD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'STATUS', '0', '编辑中', 'SYSTEM', 'ENABLED', '0', to_date('10-10-2015 16:18:13', 'dd-mm-yyyy hh24:mi:ss'), '001001', '模板状态', null, 'BJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'STATUS', '1', '待审核', 'SYSTEM', 'ENABLED', '1', to_date('10-10-2015 16:18:13', 'dd-mm-yyyy hh24:mi:ss'), '001001', '模板状态', null, 'DSH');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'STATUS', '2', '已审核', 'SYSTEM', 'ENABLED', '2', to_date('10-10-2015 16:18:13', 'dd-mm-yyyy hh24:mi:ss'), '001001', '模板状态', null, 'WC');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '0', '无', 'SYSTEM', 'ENABLED', '0', to_date('10-10-2015 16:18:24', 'dd-mm-yyyy hh24:mi:ss'), '001001', '划线类型', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '1', '单线', 'SYSTEM', 'ENABLED', '1', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'DX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '2', '双线', 'SYSTEM', 'ENABLED', '2', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'SX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '3', '粗线', 'SYSTEM', 'ENABLED', '3', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'CX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '4', '点式', 'SYSTEM', 'ENABLED', '4', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'DS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '5', '虚线', 'SYSTEM', 'ENABLED', '5', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'XX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '6', '波浪线', 'SYSTEM', 'ENABLED', '6', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'BL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '7', '点-短线', 'SYSTEM', 'ENABLED', '7', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'DD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'TOPIC_UNDERLINE_TYPE', '8', '点-点-短线', 'SYSTEM', 'ENABLED', '8', to_date('10-10-2015 16:18:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '下划线类型', null, 'DDD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'WRITE_FLAG', '0', '多次书写', 'SYSTEM', 'ENABLED', '0', to_date('10-10-2015 16:18:41', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历书写次数', null, 'DCSX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'WRITE_FLAG', '1', '单次书写', 'SYSTEM', 'ENABLED', '1', to_date('10-10-2015 16:18:41', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历书写次数', null, 'DCSX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'TEMPLET', 'WRITE_FLAG', '2', '首次单次书写', 'SYSTEM', 'ENABLED', '2', to_date('10-10-2015 16:18:41', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历书写次数', null, 'SCDCSX');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CLINIC_DISEASE_', 'TYPE', '0', '中医', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:31:52', 'dd-mm-yyyy hh24:mi:ss'), '001001', '类别', null, 'ZY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CLINIC_DISEASE_', 'TYPE', '1', '西医', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:31:53', 'dd-mm-yyyy hh24:mi:ss'), '001001', '类别', null, 'XY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CLINIC_DISEASE_', 'TYPE', '2', '手术', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:31:53', 'dd-mm-yyyy hh24:mi:ss'), '001001', '类别', null, 'SS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DATA_ELEMENT', 'ENABLED', '1', '已启用', 'SYSTEM', 'ENABLED', '1', to_date('27-10-2015 20:24:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否启用', null, 'YQY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DATA_ELEMENT', 'ENABLED', '0', '未启用', 'SYSTEM', 'ENABLED', '2', to_date('27-10-2015 20:24:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否启用', null, 'WQY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MACRO', 'TYPE', '0', '宏', 'SYSTEM', 'ENABLED', '0', to_date('29-10-2015 16:28:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '宏类型', null, 'H');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MACRO', 'TYPE', '1', '替换', 'SYSTEM', 'ENABLED', '1', to_date('29-10-2015 16:28:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '宏类型', null, 'TH');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'AUTO_APPLY', '0', '病案室审批', 'SYSTEM', 'ENABLED', '1', to_date('02-11-2015 17:42:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否自定义', null, 'F');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'AUTO_APPLY', '1', '自动审批', 'SYSTEM', 'ENABLED', '2', to_date('02-11-2015 17:42:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否自定义', null, 'S');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'STATUS', '0', '待审核', 'SYSTEM', 'ENABLED', '1', to_date('02-11-2015 18:10:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审核', null, 'F');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'STATUS', '1', '已审核', 'SYSTEM', 'ENABLED', '2', to_date('02-11-2015 18:10:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审核', null, 'S');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'STATUS', '2', '已拒绝', 'SYSTEM', 'ENABLED', '2', to_date('02-11-2015 18:10:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审核', null, 'S');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'STATUS', '3', '已归还', 'SYSTEM', 'ENABLED', '3', to_date('04-11-2015 10:49:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '状态', null, 'S');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'STATUS', '4', '已接收', 'SYSTEM', 'ENABLED', '3', to_date('04-11-2015 10:49:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '状态', null, 'S');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'AUTO_APPLY ', '1', '自动审批', 'SYSTEM', 'ENABLED', '2', to_date('26-10-2015 09:54:33', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审批类别', null, 'ZDSP');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_TEMPLET', 'TYPE', '0', '母板', 'SYSTEM', 'ENABLED', '0', to_date('17-11-2015 17:19:32', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单类型', null, 'MB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY_', 'POST_SIGN', '0', '否', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:32:56', 'dd-mm-yyyy hh24:mi:ss'), '001001', '邮寄标记', null, 'F');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY_', 'POST_SIGN', '1', '是', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:32:56', 'dd-mm-yyyy hh24:mi:ss'), '001001', '邮寄标记', null, 'S');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PRINT_DETAILS_', 'PRINT_PAGE_TYPE', '1', '奇数页打印', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:33:04', 'dd-mm-yyyy hh24:mi:ss'), '001001', '打印方式', null, 'JSY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PRINT_DETAILS_', 'PRINT_PAGE_TYPE', '2', '偶数页打印', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:33:04', 'dd-mm-yyyy hh24:mi:ss'), '001001', '打印方式', null, 'OSY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_TEMPLET', 'TYPE', '1', '西医', 'SYSTEM', 'ENABLED', '1', to_date('17-11-2015 17:19:32', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单类型', null, 'XY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_TEMPLET', 'TYPE', '2', '中医', 'SYSTEM', 'ENABLED', '2', to_date('17-11-2015 17:19:32', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单类型', null, 'ZY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'OPERATOR_TYPE', '0', '新建', 'SYSTEM', 'ENABLED', '1', to_date('17-11-2015 16:26:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'GENERAL_FIELD', 'SURE_PREFIX', '0', '有', 'SYSTEM', 'ENABLED', '0', to_date('07-11-2015 16:51:42', 'dd-mm-yyyy hh24:mi:ss'), '001001', '编辑器元素前缀', null, 'Y');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'GENERAL_FIELD', 'DENY_PREFIX', '0', '无', 'SYSTEM', 'ENABLED', '0', to_date('07-11-2015 16:51:42', 'dd-mm-yyyy hh24:mi:ss'), '001001', '编辑器元素前缀', null, 'W');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'GENERAL_FIELD', 'SURE_PREFIX', '1', '伴', 'SYSTEM', 'ENABLED', '1', to_date('07-11-2015 16:51:42', 'dd-mm-yyyy hh24:mi:ss'), '001001', '编辑器元素前缀', null, 'B');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'GENERAL_FIELD', 'SURE_PREFIX', '2', '伴有', 'SYSTEM', 'ENABLED', '2', to_date('07-11-2015 16:51:42', 'dd-mm-yyyy hh24:mi:ss'), '001001', '编辑器元素前缀', null, 'BY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_TEMPLET', 'TYPE', '3', '婴儿', 'SYSTEM', 'ENABLED', '3', to_date('17-11-2015 17:19:33', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单类型', null, 'YE');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'OPERATOR_TYPE', '1', '修改', 'SYSTEM', 'ENABLED', '2', to_date('17-11-2015 16:26:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'OPERATOR_TYPE', '2', '打印', 'SYSTEM', 'ENABLED', '3', to_date('17-11-2015 16:26:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'FINISH_STATUS', '0', '修改', 'SYSTEM', 'ENABLED', '1', to_date('17-11-2015 16:27:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'FINISH_STATUS', '1', '完成', 'SYSTEM', 'ENABLED', '2', to_date('17-11-2015 16:27:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'BACK_TYPE', '0', '文书', 'SYSTEM', 'ENABLED', '1', to_date('17-11-2015 16:27:51', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'BACK_TYPE', '1', '首页', 'SYSTEM', 'ENABLED', '2', to_date('17-11-2015 16:27:51', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_TREAMENT_APPLY_', 'APPLY_TYPE', 'KK', '跨科', 'SYSTEM', 'ENABLED', '1', to_date('19-10-2015 15:07:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '处置类型', null, 'KK');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_TREAMENT_APPLY_', 'APPLY_TYPE', 'HZ', '会诊', 'SYSTEM', 'ENABLED', '2', to_date('19-10-2015 15:07:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '处置类型', null, 'HZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_TREAMENT_APPLY_', 'APPLY_TYPE', 'YY', '营养', 'SYSTEM', 'ENABLED', '3', to_date('19-10-2015 15:07:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '处置类型', null, 'YY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'TYPE', '1', '门诊', 'SYSTEM', 'ENABLED', '1', to_date('19-10-2015 16:24:44', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历类型', null, 'MZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'BACK_TYPE', '2', '文书+首页', 'SYSTEM', 'ENABLED', '3', to_date('17-11-2015 16:27:51', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_BORROW', 'AUTO_APPLY ', '0', '病案室审批', 'SYSTEM', 'ENABLED', '2', to_date('26-10-2015 09:54:33', 'dd-mm-yyyy hh24:mi:ss'), '001001', '审批类别', null, 'BASSP');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'IS_BACK', '0', '召回', 'SYSTEM', 'ENABLED', '1', to_date('17-11-2015 16:28:56', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'GENERAL_FIELD', 'ENABLED', '0', '已禁用', 'SYSTEM', 'ENABLED', '0', to_date('24-10-2015 13:25:03', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否启用', null, 'JY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'GENERAL_FIELD', 'ENABLED', '1', '已启用', 'SYSTEM', 'ENABLED', '1', to_date('24-10-2015 13:25:03', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否启用', null, 'QY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'IS_BACK', '1', '病案室打回', 'SYSTEM', 'ENABLED', '2', to_date('17-11-2015 16:28:56', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'CLINIC_TYPE', '0', '医疗护理', 'SYSTEM', 'ENABLED', '1', to_date('17-11-2015 16:29:30', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'CLINIC_TYPE', '1', '临床护理', 'SYSTEM', 'ENABLED', '2', to_date('17-11-2015 16:29:30', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'STATUS', '0', '申请', 'SYSTEM', 'ENABLED', '1', to_date('17-11-2015 16:31:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'STATUS', '1', '批准', 'SYSTEM', 'ENABLED', '2', to_date('17-11-2015 16:31:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_WITHDRAW', 'STATUS', '2', '作废', 'SYSTEM', 'ENABLED', '3', to_date('17-11-2015 16:31:21', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_OPEN', 'DOC_MODE', '1', '编辑', 'SYSTEM', 'ENABLED', '0', to_date('06-01-2016 16:56:13', 'dd-mm-yyyy hh24:mi:ss'), '001001', '编辑器模式', null, 'BJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_OPEN', 'DOC_MODE', '2', '只读', 'SYSTEM', 'ENABLED', '1', to_date('06-01-2016 16:56:14', 'dd-mm-yyyy hh24:mi:ss'), '001001', '编辑器模式', null, 'ZD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_OPEN', 'DOC_MODE', '3', '整洁', 'SYSTEM', 'ENABLED', '2', to_date('06-01-2016 16:56:14', 'dd-mm-yyyy hh24:mi:ss'), '001001', '编辑器模式', null, 'ZJXS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_POST', 'POST_STATUS ', '0', '登记', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'HZBR');
commit;
prompt 100 records committed...
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_POST', 'POST_STATUS', '1', '装包', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'HZDLR');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_POST', 'POST_STATUS', '2', '寄送', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'HZJS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '1', '门（急）诊病历', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '2', '化验单', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '9', '手术及麻醉记录单', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '3', '住院志（即入院记录）', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '6', '医学影像检查资料', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '10', '病理报告', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '4', '体温单', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '7', '特殊检查同意书', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '11', '护理记录', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '5', '医嘱单', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '8', '手术同意书', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'EMR_CLASS', '12', '出院记录', 'SYSTEM', 'ENABLED', '1', to_date('08-12-2015 10:23:43', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'FILE_PLACE', '0', '科室', 'SYSTEM', 'ENABLED', '4', to_date('26-01-2016 17:40:15', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'FILE_PLACE', '1', '签收部门', 'SYSTEM', 'ENABLED', '5', to_date('26-01-2016 17:40:15', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'FILE_PLACE', '2', '编目部门', 'SYSTEM', 'ENABLED', '6', to_date('26-01-2016 17:40:15', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'FILE_PLACE', '3', '质控部门', 'SYSTEM', 'ENABLED', '7', to_date('26-01-2016 17:40:15', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CASE_REGISTER', 'REGISTER_STATUS', '5', '已返修', 'SYSTEM', 'ENABLED', '1', to_date('26-01-2016 18:15:51', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'YQS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'TYPE', '0', '住院', 'USER', 'ENABLED', '0', to_date('30-09-2015 10:30:32', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历类型', null, 'ZY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'FLAG', '0', '完整模板', 'USER', 'ENABLED', '0', to_date('30-09-2015 10:47:30', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历类型', null, 'WZMB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'FLAG', '1', '片段模板', 'USER', 'ENABLED', '1', to_date('30-09-2015 10:47:30', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历类型', null, 'PDMB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'FLAG', '2', '图库', 'USER', 'ENABLED', '2', to_date('30-09-2015 10:47:30', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历类型', null, 'TK');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_TREAMENT_APPLY_', 'STATUS', '1', '待处理', 'SYSTEM', 'ENABLED', '2', to_date('15-10-2015 21:16:49', 'dd-mm-yyyy hh24:mi:ss'), '001001', '类别', null, 'DCL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_TREAMENT_APPLY_', 'STATUS', '2', '处理完成', 'SYSTEM', 'ENABLED', '3', to_date('15-10-2015 21:16:49', 'dd-mm-yyyy hh24:mi:ss'), '001001', '类别', null, 'CLWC');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'TOPIC_TITLE', '231', '科主任', 'SYSTEM', 'ENABLED', '0', to_date('21-10-2015 10:54:15', 'dd-mm-yyyy hh24:mi:ss'), '001001', '职称', null, 'KZR');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'TOPIC_TITLE', '232', '主任医师', 'SYSTEM', 'ENABLED', '1', to_date('21-10-2015 10:54:16', 'dd-mm-yyyy hh24:mi:ss'), '001001', '职称', null, 'ZRYS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'TOPIC_TITLE', '233', '副主任医师', 'SYSTEM', 'ENABLED', '2', to_date('21-10-2015 10:54:16', 'dd-mm-yyyy hh24:mi:ss'), '001001', '职称', null, 'FZRYS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'TOPIC_TITLE', '234', '主治医师', 'SYSTEM', 'ENABLED', '3', to_date('21-10-2015 10:54:16', 'dd-mm-yyyy hh24:mi:ss'), '001001', '职称', null, 'ZZYS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'TOPIC_TITLE', '235', '住院医师', 'SYSTEM', 'ENABLED', '4', to_date('21-10-2015 10:54:16', 'dd-mm-yyyy hh24:mi:ss'), '001001', '职称', null, 'ZYYS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DISEASE_GROUP_DETAILS', 'TYPE', '1', '西医诊断', 'SYSTEM', 'ENABLED', '1', to_date('25-11-2015 16:40:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否西医诊断', null, 'XYZD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DISEASE_GROUP_DETAILS', 'TYPE', '2', '中医病', 'SYSTEM', 'ENABLED', '2', to_date('25-11-2015 16:40:55', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否中医病', null, 'ZYB');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_TEMPLET', 'TYPE', '4', '疼痛', 'SYSTEM', 'ENABLED', '4', to_date('17-11-2015 17:19:33', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单类型', null, 'TT');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_BORROW', 'BORROW_TYPE', 'GR', '个人', 'SYSTEM', 'ENABLED', '1', to_date('24-11-2015 16:05:57', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_BORROW', 'BORROW_TYPE', 'BM', '部门', 'SYSTEM', 'ENABLED', '1', to_date('24-11-2015 16:05:57', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_BORROW', 'BORROW_PURPOSE', '1', '患者再入院', 'SYSTEM', 'ENABLED', '1', to_date('24-11-2015 16:05:57', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_BORROW', 'BORROW_PURPOSE', '2', '查看遗传病史', 'SYSTEM', 'ENABLED', '1', to_date('24-11-2015 16:05:57', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'ZZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_MAINTAIN_APPLY', 'APPLY_REASON', '1', '病历修改', 'SYSTEM', 'ENABLED', '1', to_date('27-11-2015 21:27:38', 'dd-mm-yyyy hh24:mi:ss'), '001001', '申请原因', null, 'BLXG');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_MAINTAIN_APPLY', 'APPLY_REASON', '2', '病历删除', 'SYSTEM', 'ENABLED', '1', to_date('27-11-2015 21:27:38', 'dd-mm-yyyy hh24:mi:ss'), '001001', '申请原因', null, 'BLSC');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '7', '病案归档', 'SYSTEM', 'ENABLED', '7', to_date('11-10-2015 14:08:05', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '0', '书写', 'SYSTEM', 'ENABLED', '0', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '1', '科室质控', 'SYSTEM', 'ENABLED', '1', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '2', '病历完成', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '3', '病案签收', 'SYSTEM', 'ENABLED', '3', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '4', '终末质控', 'SYSTEM', 'ENABLED', '4', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '5', '病案签收', 'SYSTEM', 'ENABLED', '5', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_DOCTOR_PART_STATUS', '6', '病案编目', 'SYSTEM', 'ENABLED', '6', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '0', '书写', 'SYSTEM', 'ENABLED', '0', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '1', '科室质控', 'SYSTEM', 'ENABLED', '1', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '2', '病历完成', 'SYSTEM', 'ENABLED', '2', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '3', '病案签收', 'SYSTEM', 'ENABLED', '3', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '4', '终末质控', 'SYSTEM', 'ENABLED', '4', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '5', '病案签收', 'SYSTEM', 'ENABLED', '5', to_date('11-10-2015 14:09:48', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '6', '病案编目', 'SYSTEM', 'ENABLED', '6', to_date('11-10-2015 14:09:49', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'MR_NURSE_PART_STATUS', '7', '病案归档', 'SYSTEM', 'ENABLED', '7', to_date('11-10-2015 14:09:49', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_TREAMENT_APPLY_', 'STATUS', '0', '草稿', 'SYSTEM', 'ENABLED', '1', to_date('15-10-2015 21:16:49', 'dd-mm-yyyy hh24:mi:ss'), '001001', '类别', null, 'CG');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'BUTTON', 'TYPE', '1', '诊断', 'SYSTEM', 'ENABLED', '1', to_date('11-01-2016 11:52:56', 'dd-mm-yyyy hh24:mi:ss'), '001001', '按钮类型', null, 'HLJL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DISEASE_GROUP_DETAILS', 'TYPE', '0', '手术', 'SYSTEM', 'ENABLED', '0', to_date('25-11-2015 16:40:54', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否手术', null, 'SS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'DISEASE_GROUP_DETAILS', 'TYPE', '3', '中医症', 'SYSTEM', 'ENABLED', '3', to_date('25-11-2015 16:40:55', 'dd-mm-yyyy hh24:mi:ss'), '001001', '是否中医症', null, 'ZYZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CASE_REGISTER', 'REGISTER_STATUS', '0', '新建', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 08:50:13', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'XJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_MAINTAIN_APPLY', 'APPLY_REASON', '0', '病历打开异常', 'SYSTEM', 'ENABLED', '0', to_date('27-11-2015 21:27:38', 'dd-mm-yyyy hh24:mi:ss'), '001001', '申请原因', null, 'BLDKYC');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CASE_REGISTER', 'REGISTER_STATUS', '1', '待登记', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 08:50:13', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'DDJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CASE_REGISTER', 'REGISTER_STATUS', '2', '已登记', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 08:50:13', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'YDJ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'APPLYER_TYPE', '1', '患者本人', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 17:40:28', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'HZBR');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'APPLYER_TYPE', '2', '患者代理人', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 17:40:28', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'HZDLR');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'APPLYER_TYPE', '3', '患者家属', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 17:40:28', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'HZJS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'APPLYER_TYPE', '4', '保险机构', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 17:40:28', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'BXJG');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'APPLYER_TYPE', '5', '公安、司法机构执行人员', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 17:40:28', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CASE_REGISTER', 'REGISTER_STATUS', '3', '已签收', 'SYSTEM', 'ENABLED', '1', to_date('30-11-2015 19:40:25', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'YQS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_MODIFY_APPLY', 'APPLY_REASON', '1', '内容修改', 'SYSTEM', 'ENABLED', '1', to_date('02-12-2015 20:04:11', 'dd-mm-yyyy hh24:mi:ss'), '001001', '申请原因', null, 'NRXG');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_MODIFY_APPLY', 'APPLY_REASON', '0', '版面调整', 'SYSTEM', 'ENABLED', '0', to_date('02-12-2015 20:04:11', 'dd-mm-yyyy hh24:mi:ss'), '001001', '申请原因', null, 'BMTZ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_MODIFY_APPLY', 'APPLY_REASON', '2', '其他原因', 'SYSTEM', 'ENABLED', '2', to_date('02-12-2015 20:04:11', 'dd-mm-yyyy hh24:mi:ss'), '001001', '申请原因', null, 'QTYY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE_MODIFY_APPLY', 'APPLY_REASON', '3', '内容错误', 'SYSTEM', 'ENABLED', '3', to_date('02-12-2015 20:04:11', 'dd-mm-yyyy hh24:mi:ss'), '001001', '申请原因', null, 'NRCW');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'COPY_FLAG', '0', '未复印', 'SYSTEM', 'ENABLED', '1', to_date('28-01-2016 18:20:28', 'dd-mm-yyyy hh24:mi:ss'), '001001', '打印标志', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'COPY_FLAG', '1', '已复印', 'SYSTEM', 'ENABLED', '1', to_date('28-01-2016 18:20:28', 'dd-mm-yyyy hh24:mi:ss'), '001001', '打印标志', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_CLASS', 'FLAG', '3', '体温单', 'SYSTEM', 'ENABLED', '3', to_date('11-12-2015 10:48:23', 'dd-mm-yyyy hh24:mi:ss'), '001001', '病历类型标志', null, 'TWD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_SQL', 'TYPE', 'HEADERLABEL', '页眉标签', 'SYSTEM', 'ENABLED', '0', to_date('18-12-2015 17:38:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单SQL类型', null, 'YMBQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_SQL', 'TYPE', 'HEADERLINE', '页眉数据行', 'SYSTEM', 'ENABLED', '1', to_date('18-12-2015 17:38:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单SQL类型', null, 'YMSJH');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_SQL', 'TYPE', 'TICK', '时间刻度', 'SYSTEM', 'ENABLED', '2', to_date('18-12-2015 17:38:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单SQL类型', null, 'SJKD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'VITAL_SQL', 'TYPE', 'ITEMDATA', '项目数据', 'SYSTEM', 'ENABLED', '3', to_date('18-12-2015 17:38:29', 'dd-mm-yyyy hh24:mi:ss'), '001001', '体温单SQL类型', null, '项目数据');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'POST_SIGN', '0', '否', 'SYSTEM', 'ENABLED', '1', to_date('10-12-2015 09:57:44', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_MR_COPY', 'POST_SIGN', '1', '是', 'SYSTEM', 'ENABLED', '1', to_date('10-12-2015 09:57:44', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'GASFJGZXRY');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_BORROW', 'RETURN_TYPE', '0', '正常', 'SYSTEM', 'ENABLED', '1', to_date('26-01-2016 08:46:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '归还类型', null, 'ZC');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_BORROW', 'RETURN_TYPE', '1', '遗失', 'SYSTEM', 'ENABLED', '1', to_date('26-01-2016 08:46:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '归还类型', null, 'YS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'EMR_PAPER_BORROW', 'RETURN_TYPE', '2', '损毁', 'SYSTEM', 'ENABLED', '1', to_date('26-01-2016 08:46:20', 'dd-mm-yyyy hh24:mi:ss'), '001001', '归还类型', null, 'SH');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'FILE_FLAG', '0', '草稿', 'SYSTEM', 'ENABLED', '0', to_date('23-12-2015 11:23:19', 'dd-mm-yyyy hh24:mi:ss'), '001001', '文件标识', null, 'CG');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'FILE_FLAG', '1', '经治审签', 'SYSTEM', 'ENABLED', '1', to_date('23-12-2015 11:23:19', 'dd-mm-yyyy hh24:mi:ss'), '001001', '文件标识', null, 'JZSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'FILE_FLAG', '2', '主治审签', 'SYSTEM', 'ENABLED', '2', to_date('23-12-2015 11:23:19', 'dd-mm-yyyy hh24:mi:ss'), '001001', '文件标识', null, 'ZZSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'FILE_FLAG', '3', '主任审签', 'SYSTEM', 'ENABLED', '3', to_date('23-12-2015 11:23:19', 'dd-mm-yyyy hh24:mi:ss'), '001001', '文件标识', null, 'ZRSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'FILE_FLAG', '4', '科主任审签', 'SYSTEM', 'ENABLED', '4', to_date('23-12-2015 11:23:19', 'dd-mm-yyyy hh24:mi:ss'), '001001', '文件标识', null, 'KZRSQ');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'MR_FILE', 'FILE_FLAG', 'T', '草稿审签过', 'SYSTEM', 'ENABLED', '6', to_date('23-12-2015 11:23:19', 'dd-mm-yyyy hh24:mi:ss'), '001001', '文件标识', null, 'CGSQG');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'CASE_REGISTER', 'REGISTER_STATUS', '4', '已归档', 'SYSTEM', 'ENABLED', '1', to_date('27-01-2016 11:03:01', 'dd-mm-yyyy hh24:mi:ss'), '001001', '字典类型', null, 'YQS');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT', 'FILE_PLACE', '4', '签收部门', 'SYSTEM', 'ENABLED', '7', to_date('27-01-2016 08:53:50', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'BUTTON', 'TYPE', '0', '护理记录', 'SYSTEM', 'ENABLED', '0', to_date('23-12-2015 12:35:56', 'dd-mm-yyyy hh24:mi:ss'), '001001', '宏类型', null, 'HLJL');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_NURSE_RECORD_', 'FILE_TYPE', '0', '护理记录单', 'SYSTEM', 'ENABLED', '0', to_date('27-01-2016 12:11:49', 'dd-mm-yyyy hh24:mi:ss'), '001001', '护理记录单', null, 'HLJLD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'NR_CONTENT_IO_AMOUNT_', 'FILE_TYPE', '1', '护理评估单', 'SYSTEM', 'ENABLED', '1', to_date('27-01-2016 12:11:49', 'dd-mm-yyyy hh24:mi:ss'), '001001', '护理评估单', null, 'HLPGD');
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '0', '书写', 'SYSTEM', 'ENABLED', '0', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '1', '科室质控', 'SYSTEM', 'ENABLED', '1', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '2', '病历完成', 'SYSTEM', 'ENABLED', '2', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '3', '病案签收', 'SYSTEM', 'ENABLED', '3', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
commit;
prompt 200 records committed...
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '4', '终末质控', 'SYSTEM', 'ENABLED', '4', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '5', '病案签收', 'SYSTEM', 'ENABLED', '5', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '6', '病案编目', 'SYSTEM', 'ENABLED', '6', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_DOCTOR_PART_STATUS', '7', '病案归档', 'SYSTEM', 'ENABLED', '7', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '医生部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '0', '书写', 'SYSTEM', 'ENABLED', '0', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '1', '科室质控', 'SYSTEM', 'ENABLED', '1', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '2', '病历完成', 'SYSTEM', 'ENABLED', '2', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '3', '病案签收', 'SYSTEM', 'ENABLED', '3', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '4', '终末质控', 'SYSTEM', 'ENABLED', '4', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '5', '病案签收', 'SYSTEM', 'ENABLED', '5', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '6', '病案编目', 'SYSTEM', 'ENABLED', '6', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'MR_NURSE_PART_STATUS', '7', '病案归档', 'SYSTEM', 'ENABLED', '7', to_date('09-03-2016 13:25:37', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '护士部分病案状态', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'FILE_PLACE', '0', '科室', 'SYSTEM', 'ENABLED', '4', to_date('09-03-2016 13:25:38', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'FILE_PLACE', '1', '签收部门', 'SYSTEM', 'ENABLED', '5', to_date('09-03-2016 13:25:38', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'FILE_PLACE', '2', '编目部门', 'SYSTEM', 'ENABLED', '6', to_date('09-03-2016 13:25:38', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'FILE_PLACE', '3', '质控部门', 'SYSTEM', 'ENABLED', '7', to_date('09-03-2016 13:25:38', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
insert into FIELD_DICT (OWNER, TABLE_NAME, FIELD_NAME, FIELD_VALUE, FIELD_MEAN, TYPE, STATUS, SEQ_NO, UPDATE_DATE, OPERATOR, REMARK, WUBICODE, PINYIN)
values ('HSEMR', 'PATIENT_VISIT_', 'FILE_PLACE', '4', '签收部门', 'SYSTEM', 'ENABLED', '7', to_date('09-03-2016 13:25:38', 'dd-mm-yyyy hh24:mi:ss'), 'HSEMR', '病案当前所在部门', null, null);
commit;
prompt 217 records loaded
prompt Enabling triggers for FIELD_DICT...
alter table FIELD_DICT enable all triggers;
set feedback on
set define on
prompt Done.
